pipeline {
    agent any

    tools {
        maven 'maven 3.6.1'
    }

    stages {
        stage("build") {
            steps {
                echo "app compilation..."
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage("test"){
            steps {
                echo "unit tests..."
                dir('worker'){
                    sh 'mvn clean test'
                }
            }

        }
        stage("package"){
            steps {
                echo 'app packaging...'
                dir('worker'){
                    sh 'mvn package -Dskiptests'
                }
            }
        }

    }

    post{
        always{
            echo "test, build and package completed!"
            archiveArtifacts artifacts: '**/target/*.jar',
            fingerprint: true
        }

    }
}