pipeline {
    agent any

    tools {
        maven 'maven 3.6.1'
    }

    stages {
        stage("build") {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo "app compilation..."
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage("test"){
            when {
                changeset "**/worker/**"
            }
            steps {
                echo "unit tests..."
                dir('worker'){
                    sh 'mvn clean test'
                }
            }

        }
        stage("package"){
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'app packaging...'
                dir('worker'){
                    sh 'mvn package -Dskiptests'
                    archiveArtifacts artifacts: '**/target/*.jar',
                    fingerprint: true
                }
            }
        }

    }

    post{
        always{
            echo "test, build and package completed!"
        }

    }
}